In [37]:
import torch

In [38]:
tensor1 = torch.arange(10)
tensor1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
tensor1 = tensor1.reshape(2,5)
tensor1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [40]:
tensor2 = tensor1.reshape(2,-1)
tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [41]:
tensor1[0][1] = 420
tensor1

tensor([[  0, 420,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [42]:
tensor2

tensor([[  0, 420,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [43]:
tensor3 = tensor1[:,1]
tensor3

tensor([420,   6])

In [44]:
tensor4 = tensor1[1,:]
tensor4

tensor([5, 6, 7, 8, 9])