In [1]:
import numpy as np

In [2]:
#Array creation
x1 = np.array(range(0,10))
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x2 = np.ones((3,3))
x2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
x3 = np.full((4,2),7)
x3

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [5]:
x4 = np.identity(5)
x4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
x5 = np.linspace(-1,1,20)
x5.reshape((20,1))

array([[-1.        ],
       [-0.89473684],
       [-0.78947368],
       [-0.68421053],
       [-0.57894737],
       [-0.47368421],
       [-0.36842105],
       [-0.26315789],
       [-0.15789474],
       [-0.05263158],
       [ 0.05263158],
       [ 0.15789474],
       [ 0.26315789],
       [ 0.36842105],
       [ 0.47368421],
       [ 0.57894737],
       [ 0.68421053],
       [ 0.78947368],
       [ 0.89473684],
       [ 1.        ]])

In [7]:
np.random.normal(loc = 0, scale = 1, size = (2,5))

array([[-1.48885815, -0.47697554, -0.14256147, -2.25985969, -1.80011296],
       [-0.79575273,  0.69248827,  0.05643943,  1.34626518,  0.36004512]])

In [8]:
x4[:,[1,3,3]] = x4[:,[2,4,0]]
x4

array([[1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
x6 = np.array([1,3,1,3])
x7 = np.array([3,3,3,4])
x6 * x7

array([ 3,  9,  3, 12])

In [10]:
np.sum(x6)

np.int64(8)

In [11]:
np.random.randint(-10,10,(5,5))

array([[-10,  -9,  -8,  -4,   1],
       [  9,   1,  -8,  -4,   6],
       [  5,  -2,   1,   8,   3],
       [ -9,   0,   9,   5,  -5],
       [  8,   3,  -2,  -9,  -7]], dtype=int32)

In [12]:
np.arange(0,12).reshape(4,3) + np.array([1,2,1])

array([[ 1,  3,  3],
       [ 4,  6,  6],
       [ 7,  9,  9],
       [10, 12, 12]])

In [13]:
np.cumulative_sum(np.arange(1,12))

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [14]:
x8 = np.arange(1,17)
x8 = x8.reshape(4,4)
x8

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
x8.flatten('F')

array([ 1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15,  4,  8, 12, 16])

In [16]:
np.tile([[1,0],[0,1]], (5))

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [17]:
np.where(x8%2==1, 0, x8)

array([[ 0,  2,  0,  4],
       [ 0,  6,  0,  8],
       [ 0, 10,  0, 12],
       [ 0, 14,  0, 16]])

In [18]:
import pandas as pd

In [20]:
a1 = pd.Series([10,11,12,13], index = ['a','b','c','d'])
a1

a    10
b    11
c    12
d    13
dtype: int64

In [22]:
path = "C:/Users/addhu/Downloads/people.csv"

In [23]:
people = pd.read_csv(path)
people

id   name  score
0   1  Alice     85
1   2    Bob     90
2   3  Cathy     78
3   4  David     92
4   5    Eva     88

In [25]:
myDict = {"name":["Alicia", "Bob", "Charlie"],
          "age":[25,30,35],
          "city":["NY", "LA", "Chicago"]}
myDict

{'name': ['Alicia', 'Bob', 'Charlie'],
 'age': [25, 30, 35],
 'city': ['NY', 'LA', 'Chicago']}

In [53]:
a2 = pd.DataFrame(myDict)
a2

name  age     city
0   Alicia   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago

In [58]:
a2.loc[:, ["age","city"]]

age     city
0   25       NY
1   30       LA
2   35  Chicago

In [37]:
a2.columns

Index(['name', 'age', 'city'], dtype='object')

In [45]:
print(a1.get(2))

12


C:\Users\addhu\AppData\Local\Temp\ipykernel_26944\2036727451.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(a1.get(2))


In [46]:
a1.describe()

count     4.000000
mean     11.500000
std       1.290994
min      10.000000
25%      10.750000
50%      11.500000
75%      12.250000
max      13.000000
dtype: float64

In [47]:
a1.info()

<class 'pandas.core.series.Series'>
Index: 4 entries, a to d
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      int64
dtypes: int64(1)
memory usage: 236.0+ bytes


In [69]:
a2[(a2["age"] > 25) & (a2["city"] != "LA")]

name  age     city
2  Charlie   35  Chicago

In [81]:
a2.sort_index(axis=0, ascending=False)

name  age     city
2  Charlie   35  Chicago
1      Bob   30       LA
0   Alicia   25       NY

In [83]:
a2[a2['category'].isin(['A','B','C'])]


KeyError: 'category'