In [9]:
import torch, torchvision, torchaudio
import numpy
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)

In [10]:
x1 = torch.zeros(5)
x1

tensor([0., 0., 0., 0., 0.])

In [11]:

x2 = torch.tensor([[1,1,1],[1,1,1]])
x2

tensor([[1, 1, 1],
        [1, 1, 1]])

In [12]:
x3 = torch.ones(2,2,dtype=float)
x3

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [13]:
x4 = torch.randint(1,70,size=(3,3))
x4

tensor([[30, 14, 11],
        [38,  5, 34],
        [41, 13,  6]])

In [14]:
x5 = torch.tensor([[1,2,3],[4,5,6]])
x5

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
print(f'{str(x1.shape)} {str(x1.dtype)} {str(x1.device)}')

torch.Size([5]) torch.float32 cpu


In [16]:
print(f'{str(x2.shape)} {str(x2.dtype)} {str(x2.device)}')

torch.Size([2, 3]) torch.int64 cpu


In [17]:
print(f'{str(x3.shape)} {str(x3.dtype)} {str(x3.device)}')

torch.Size([2, 2]) torch.float64 cpu


In [18]:
print(f'{str(x4.shape)} {str(x4.dtype)} {str(x4.device)}')

torch.Size([3, 3]) torch.int64 cpu


In [19]:
print(f'{str(x5.shape)} {str(x5.dtype)} {str(x5.device)}')

torch.Size([2, 3]) torch.int64 cpu


In [20]:
x6 = x4.reshape(9)
x6

tensor([30, 14, 11, 38,  5, 34, 41, 13,  6])

In [21]:
x7 = x4.view(9)
x7

tensor([30, 14, 11, 38,  5, 34, 41, 13,  6])

In [22]:
x8 = x4.view(9,1)
x8

tensor([[30],
        [14],
        [11],
        [38],
        [ 5],
        [34],
        [41],
        [13],
        [ 6]])

In [23]:
x9 = x2 + x5
x9

tensor([[2, 3, 4],
        [5, 6, 7]])

In [24]:
x4 * x4

tensor([[ 900,  196,  121],
        [1444,   25, 1156],
        [1681,  169,   36]])

In [25]:
x4 / x4

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
x4.mul_(x4)
x4

tensor([[ 900,  196,  121],
        [1444,   25, 1156],
        [1681,  169,   36]])

In [27]:
x10 = x2.matmul(x4)
x10

tensor([[4025,  390, 1313],
        [4025,  390, 1313]])

In [28]:
x11 = torch.tensor([1.8, 1], dtype=int)
x11

tensor([1, 1])

In [29]:
x11.dtype

torch.int64

In [30]:
x12 = torch.tensor([1,1,10])
x4

tensor([[ 900,  196,  121],
        [1444,   25, 1156],
        [1681,  169,   36]])

In [31]:
x4.add(x12.view(x12.shape[0],1))

tensor([[ 901,  197,  122],
        [1445,   26, 1157],
        [1691,  179,   46]])

In [32]:
print(torch.tensor([[[1]]]).dim())

3


In [33]:
t = torch.arange(0,16).view(4,4)
t

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [34]:
t[1]

tensor([4, 5, 6, 7])

In [35]:
t[len(t)-1]

tensor([12, 13, 14, 15])

In [36]:
i = 4
t[len(t)-i:len(t),len(t)-i:len(t)]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [37]:
x14 = torch.tensor(2.0, requires_grad=True)
y = x14 ** 2 + 3 * x14 + 1
y.backward()
x14.grad

tensor(7.)

In [38]:
x15 = torch.randn(3, requires_grad = True)
x15

tensor([-0.6334,  0.6267,  2.0766], requires_grad=True)

In [39]:
y = x15.dot(x15)
y.backward()
x15.grad

tensor([-1.2667,  1.2533,  4.1531])

In [40]:
true_w, true_b = 2.0, -1.0
X = torch.linspace(0,1,160).reshape(160,1)
y = true_w * X + true_b + 0.1 + torch.randn_like(X)

In [41]:
class PracNet(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.w = torch.nn.Parameter(torch.randn(1, requires_grad = True))
        self.b = torch.nn.Parameter(torch.randn(1, requires_grad = True))
    def forward(self,x):
        return self.w * x + self.b
model = PracNet()

In [42]:
msl = torch.nn.MSELoss(reduction='mean')
for i in range(200):
    y_pred = model.forward(X)
    loss = torch.mean((y_pred-y)**2)
    loss.backward()
    with torch.no_grad():
        model.w -= 0.1 * model.w.grad
        model.b -= 0.1 * model.b.grad
    model.w.grad.zero_()
    model.b.grad.zero_()
model.w.item()

1.7836908102035522

In [43]:
model.b.item()

-0.670650839805603

In [44]:
model = torch.nn.Linear(1,1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.3)

In [45]:
# for i in range(100):
#     y_pred = model(X)
#     loss = loss_fn(y,y_pred)
#     optimizer.zero_grad()
#     loss.backward()
#     optimizer.step()
# for name, param in model.named_parameters():
#     print(name, param)
    

In [46]:
dataset = torch.utils.data.TensorDataset(X,y)
loader = torch.utils.data.DataLoader(dataset, batch_size = 16, shuffle = True)

for i in range(100):
    for xload, yload in loader:
        y_pred = model(xload)
        loss = loss_fn(y_pred, yload)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f'epoch:{i} loss:{loss}')

epoch:0 loss:1.0817086696624756
epoch:1 loss:1.394115924835205
epoch:2 loss:0.641568124294281
epoch:3 loss:0.8560330271720886
epoch:4 loss:1.2026084661483765
epoch:5 loss:1.1990222930908203
epoch:6 loss:0.744473934173584
epoch:7 loss:0.8258069753646851
epoch:8 loss:0.9954671263694763
epoch:9 loss:1.1599081754684448
epoch:10 loss:1.0572857856750488
epoch:11 loss:0.39973029494285583
epoch:12 loss:0.7523767948150635
epoch:13 loss:1.1685729026794434
epoch:14 loss:0.7951477766036987
epoch:15 loss:0.34491321444511414
epoch:16 loss:0.9980896711349487
epoch:17 loss:0.8061030507087708
epoch:18 loss:1.039774775505066
epoch:19 loss:0.6364051699638367
epoch:20 loss:1.4552754163742065
epoch:21 loss:1.2739040851593018
epoch:22 loss:1.47662353515625
epoch:23 loss:1.18597412109375
epoch:24 loss:1.0145444869995117
epoch:25 loss:1.3587009906768799
epoch:26 loss:0.9175710082054138
epoch:27 loss:0.533083975315094
epoch:28 loss:1.5428028106689453
epoch:29 loss:1.4799726009368896
epoch:30 loss:0.77876168489

In [47]:
X1 = torch.linspace(-1,1,200).reshape(200,1)
X1

tensor([[-1.0000],
        [-0.9899],
        [-0.9799],
        [-0.9698],
        [-0.9598],
        [-0.9497],
        [-0.9397],
        [-0.9296],
        [-0.9196],
        [-0.9095],
        [-0.8995],
        [-0.8894],
        [-0.8794],
        [-0.8693],
        [-0.8593],
        [-0.8492],
        [-0.8392],
        [-0.8291],
        [-0.8191],
        [-0.8090],
        [-0.7990],
        [-0.7889],
        [-0.7789],
        [-0.7688],
        [-0.7588],
        [-0.7487],
        [-0.7387],
        [-0.7286],
        [-0.7186],
        [-0.7085],
        [-0.6985],
        [-0.6884],
        [-0.6784],
        [-0.6683],
        [-0.6583],
        [-0.6482],
        [-0.6382],
        [-0.6281],
        [-0.6181],
        [-0.6080],
        [-0.5980],
        [-0.5879],
        [-0.5779],
        [-0.5678],
        [-0.5578],
        [-0.5477],
        [-0.5377],
        [-0.5276],
        [-0.5176],
        [-0.5075],
        [-0.4975],
        [-0.4874],
        [-0.

In [48]:
Y1 = 4*X1**3 - 2*X1**2 + 0.2*torch.randn_like(X1)
Y1

tensor([[-5.6873e+00],
        [-5.8158e+00],
        [-5.5655e+00],
        [-5.4380e+00],
        [-5.2517e+00],
        [-5.2019e+00],
        [-5.3227e+00],
        [-5.0193e+00],
        [-4.9990e+00],
        [-4.6583e+00],
        [-4.9599e+00],
        [-4.7924e+00],
        [-3.9888e+00],
        [-4.4724e+00],
        [-4.2163e+00],
        [-3.7863e+00],
        [-3.5894e+00],
        [-3.3466e+00],
        [-3.4630e+00],
        [-3.4406e+00],
        [-3.1882e+00],
        [-3.1000e+00],
        [-2.8616e+00],
        [-3.2841e+00],
        [-2.6050e+00],
        [-2.8791e+00],
        [-2.8172e+00],
        [-2.7772e+00],
        [-2.4800e+00],
        [-2.6152e+00],
        [-2.1428e+00],
        [-2.3009e+00],
        [-2.0513e+00],
        [-2.1401e+00],
        [-1.7810e+00],
        [-1.8172e+00],
        [-1.6168e+00],
        [-1.8044e+00],
        [-1.6704e+00],
        [-1.6179e+00],
        [-1.5126e+00],
        [-1.2100e+00],
        [-1.1372e+00],
        [-1

In [49]:
class neuralnetwork(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = torch.nn.Linear(1,32)
        self.relu = torch.nn.ReLU()
        self.layer2 = torch.nn.Linear(32,1)
    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        return self.layer2(x)


In [50]:
model = neuralnetwork()
lossfn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
for i in range(2000):
    y_pred = model.forward(X1)
    loss = lossfn(y_pred, Y1)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f'{i}:{loss}')



0:3.220736503601074
1:1.7755433320999146
2:1.1923143863677979
3:0.9519408345222473
4:0.8521758913993835
5:0.8060570359230042
6:0.7800287008285522
7:0.761158287525177
8:0.7452967166900635
9:0.7309711575508118
10:0.7176631689071655
11:0.7051106095314026
12:0.6932598352432251
13:0.6820997595787048
14:0.6715800762176514
15:0.6616177558898926
16:0.652108907699585
17:0.6429930329322815
18:0.6341556310653687
19:0.6256353855133057
20:0.6173720359802246
21:0.6091575026512146
22:0.6010172367095947
23:0.592983067035675
24:0.584912896156311
25:0.5768897533416748
26:0.5688921809196472
27:0.5608327388763428
28:0.5527732372283936
29:0.5446759462356567
30:0.5366434454917908
31:0.5286369919776917
32:0.5205866098403931
33:0.5125488042831421
34:0.5045240521430969
35:0.49659597873687744
36:0.488749235868454
37:0.48086634278297424
38:0.4730527102947235
39:0.46529534459114075
40:0.4575677514076233
41:0.4499025046825409
42:0.4423385560512543
43:0.4348863661289215
44:0.42756643891334534
45:0.42035195231437683

In [51]:
model.forward(X1)

tensor([[-5.8845e+00],
        [-5.7549e+00],
        [-5.6254e+00],
        [-5.4958e+00],
        [-5.3663e+00],
        [-5.2367e+00],
        [-5.1072e+00],
        [-4.9776e+00],
        [-4.8481e+00],
        [-4.7185e+00],
        [-4.5890e+00],
        [-4.4594e+00],
        [-4.3299e+00],
        [-4.2003e+00],
        [-4.0708e+00],
        [-3.9412e+00],
        [-3.8117e+00],
        [-3.6821e+00],
        [-3.5526e+00],
        [-3.4230e+00],
        [-3.2935e+00],
        [-3.1639e+00],
        [-3.0533e+00],
        [-2.9630e+00],
        [-2.8728e+00],
        [-2.7825e+00],
        [-2.6923e+00],
        [-2.6021e+00],
        [-2.5118e+00],
        [-2.4216e+00],
        [-2.3314e+00],
        [-2.2411e+00],
        [-2.1509e+00],
        [-2.0607e+00],
        [-1.9704e+00],
        [-1.8802e+00],
        [-1.7900e+00],
        [-1.7133e+00],
        [-1.6606e+00],
        [-1.6079e+00],
        [-1.5552e+00],
        [-1.5025e+00],
        [-1.4498e+00],
        [-1

In [52]:
# Download and load CIFAR-10 into a single tensor of shape (N, C, H, W)
data = torch.from_numpy(torchvision.datasets.CIFAR10('.', train=True, download=True).data).permute(0,3,1,2).float() / 255

target = torch.tensor(torchvision.datasets.CIFAR10('.',train=True,download=True).targets)

print(data.shape)  # e.g. (50000, 3, 32, 32)
data
# 50000 images
# 3 different color channels
# 32 width 
# 32 height

torch.Size([50000, 3, 32, 32])


tensor([[[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
          [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
          [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
          ...,
          [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
          [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
          [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],

         [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
          [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
          [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
          ...,
          [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
          [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
          [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],

         [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
          [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
          [0.0824, 0.0000, 0.0314,  ..., 0

In [53]:
class CNN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = torch.nn.Conv2d(3,16,3,1)
        self.conv2 = torch.nn.Conv2d(16,32,3,1)
        self.layer1 = torch.nn.Linear(32*6*6,120)
        self.layer2 = torch.nn.Linear(120,10)
        self.relu = torch.nn.ReLU()
        self.maxpool = torch.nn.MaxPool2d(2,2)
        self.flatten = torch.nn.Flatten()
    def forward(self,x):
        x = self.conv1(x)
        x = self.relu(x)
        x = self.maxpool(x)
        x = self.conv2(x)
        x = self.relu(x)
        x = self.maxpool(x)
        x = self.flatten(x)
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        return x

In [54]:
cnnmodel = CNN()
lossfunction = torch.nn.CrossEntropyLoss()
optimfunction = torch.optim.Adam(cnnmodel.parameters(), lr = 0.001)
dataset = torch.utils.data.TensorDataset(data,target)
train_loader = torch.utils.data.DataLoader(dataset, batch_size = 128, shuffle = True)
for i in range(100):
    cnnmodel.train()
    for images, targets in train_loader:
        predictions = cnnmodel(images)
        loss = lossfunction(predictions, targets)
        optimfunction.zero_grad()
        loss.backward()
        optimfunction.step()
        print(f'{i}:{loss}')


0:2.304464340209961
0:2.3054418563842773
0:2.304720640182495
0:2.3042709827423096
0:2.30049729347229
0:2.2805280685424805
0:2.299020528793335
0:2.2951858043670654
0:2.3016464710235596
0:2.2862918376922607
0:2.2863121032714844
0:2.256282091140747
0:2.3095359802246094
0:2.2621500492095947
0:2.267504930496216
0:2.2557573318481445
0:2.242785930633545
0:2.2339298725128174
0:2.2135818004608154
0:2.223182439804077
0:2.2175471782684326
0:2.1908018589019775
0:2.195754051208496
0:2.2171950340270996
0:2.210386276245117
0:2.140266180038452
0:2.158045530319214
0:2.0937674045562744
0:2.1867294311523438
0:2.1367690563201904
0:2.146503210067749
0:2.127051591873169
0:2.0810530185699463
0:2.1057567596435547
0:2.0130765438079834
0:2.0444588661193848
0:2.0604913234710693
0:1.9867804050445557
0:1.9755505323410034
0:1.9858508110046387
0:2.0616726875305176
0:2.0019443035125732
0:2.0824460983276367
0:2.0347237586975098
0:1.9423463344573975
0:2.0168540477752686
0:2.0309298038482666
0:1.9094290733337402
0:2.063

KeyboardInterrupt: 

In [ ]:
cnnmodel(data)

tensor([[-25.1784, -31.7160,   8.6334,  ...,  -2.2802, -38.3557, -64.7022],
        [  0.4592, -11.4617,  10.4390,  ..., -26.0665, -11.3114,  24.7144],
        [  4.7899,  -9.3075, -15.0694,  ..., -16.7282, -25.1943,  15.5863],
        ...,
        [  7.3786,  -5.6704, -10.3298,  ..., -22.2546,   6.3960,  10.4145],
        [  2.0046,  33.4803, -36.2681,  ...,  -6.8439,   8.3834,  17.2467],
        [-10.0456,   2.1598, -35.0873,  ..., -15.5628,   0.5372, -25.3600]],
       grad_fn=<AddmmBackward0>)

In [ ]:
def get_all_predictions(model, loader, device):
    """
    Runs the model in eval mode over the entire DataLoader and
    returns a LongTensor of shape (N,) with the predicted class index for each sample.
    """
    model.eval()
    all_preds = []
    with torch.no_grad():
        for images, _ in loader:
            images = images.to(device)
            outputs = model(images)            # shape [B, num_classes]
            _, preds = torch.max(outputs, dim=1)  # indices of max logit
            all_preds.append(preds.cpu())
    return torch.cat(all_preds, dim=0)  # shape [N]

def count_correct(preds: torch.Tensor, targets: torch.Tensor) -> int:
    """
    Given two LongTensors of shape (N,), returns the number of matching entries.
    """
    return (preds == targets).sum().item()

In [ ]:
all_preds = get_all_predictions(cnnmodel, train_loader, device)
correct   = count_correct(all_preds, target)

print(f"Correct predictions: {correct}/{len(target)}")
print(f"Accuracy: {100*correct/len(target):.2f}%")

Correct predictions: 4961/50000
Accuracy: 9.92%
