In [36]:
import torch

In [37]:
import numpy as np

In [38]:
myList = [1,2,3,4,5]
myList

[1, 2, 3, 4, 5]

In [39]:
np1 = np.random.rand(3,4)
np1

array([[0.30222785, 0.54824164, 0.81506061, 0.90456118],
       [0.18881243, 0.49116466, 0.0023382 , 0.52789373],
       [0.13240787, 0.99082903, 0.80038872, 0.43926618]])

In [40]:
type(np1)

numpy.ndarray

In [41]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3001, -0.1572, -1.4491,  1.4622],
        [ 1.8757,  0.5462,  1.1800, -0.2513],
        [ 0.6567, -0.6351, -0.5953,  0.2160]])

In [42]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [43]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3022, 0.5482, 0.8151, 0.9046],
        [0.1888, 0.4912, 0.0023, 0.5279],
        [0.1324, 0.9908, 0.8004, 0.4393]], dtype=torch.float64)

In [44]:
type(my_tensor)

torch.Tensor