In [47]:
import torch
import numpy as np

In [48]:
tensor1 = torch.tensor([1,2,3,4,5])
tensor2 = torch.tensor([6,7,8,9,10])
tensor1 + tensor2

tensor([ 7,  9, 11, 13, 15])

In [49]:
torch.add(tensor1, tensor2)

tensor([ 7,  9, 11, 13, 15])

In [50]:
tensor1 - tensor2

tensor([-5, -5, -5, -5, -5])

In [51]:
torch.sub(tensor1, tensor2)

tensor([-5, -5, -5, -5, -5])

In [52]:
torch.sub(tensor2, tensor1)

tensor([5, 5, 5, 5, 5])

In [53]:
tensor1 * tensor2

tensor([ 6, 14, 24, 36, 50])

In [54]:
torch.mul(tensor1, tensor2)

tensor([ 6, 14, 24, 36, 50])

In [55]:
tensor1 / tensor2

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [56]:
torch.div(tensor1,tensor2)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [57]:
torch.pow(tensor1, tensor2)

tensor([      1,     128,    6561,  262144, 9765625])

In [58]:
tensor1.add(tensor2)

tensor([ 7,  9, 11, 13, 15])

In [59]:
tensor1

tensor([1, 2, 3, 4, 5])

In [60]:
tensor1.add_(tensor2)

tensor([ 7,  9, 11, 13, 15])

In [61]:
tensor1

tensor([ 7,  9, 11, 13, 15])